In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('sample_data.csv')

df.head(2)

,Scan Sweep Time (Sec),Scan Number,3001 (°C)- TC1B,3002 (°C)- TC2B,3003 (°C)- TC3B,3004 (°C)- TC4B,3005 (°C)- TC5B,3006 (°C)- TC6B,3007 (°C)- TC7B,3008 (°C)- TC8B,...,7002 (Vdc)- HF2 C1 NE CORNER,7003 (Vdc)- HF3 C4 DUAL1,7004 (Vdc)- HF4 C4 ARC2,7005 (Vdc)- HF5 C3 ARC1,7006 (Vdc)- HF6 C1 N FRONT L,7007 (Vdc)- HF7 WALL,7008 (Vdc)- HF8 C3 ARC1,7009 (Vdc)- HF9 C3 ARC2,7010 (Vdc)- HF10 C3 DUAL1,7011 (Vdc)- HF11 C2 DUAL1
0,2025-11-19 22:02:13.703,1,17.121,17.284,16.990,16.949,15.796,15.578,15.607,15.462,...,8.740000e-07,-0.000004,-0.000008,-0.000003,-2.910000e-07,-0.000005,-0.000006,-0.000005,-0.00001,-0.000008
1,2025-11-19 22:02:18.274,2,17.092,17.277,16.969,16.950,15.792,15.566,15.605,15.462,...,3.494000e-06,-0.000001,-0.000003,-0.000005,1.456000e-06,-0.000002,-0.000008,-0.000008,-0.00001,-0.000004

In [11]:
df.describe()

,Scan Number,3001 (°C)- TC1B,3002 (°C)- TC2B,3003 (°C)- TC3B,3004 (°C)- TC4B,3005 (°C)- TC5B,3006 (°C)- TC6B,3007 (°C)- TC7B,3008 (°C)- TC8B,3009 (°C)- TC9B,...,7002 (Vdc)- HF2 C1 NE CORNER,7003 (Vdc)- HF3 C4 DUAL1,7004 (Vdc)- HF4 C4 ARC2,7005 (Vdc)- HF5 C3 ARC1,7006 (Vdc)- HF6 C1 N FRONT L,7007 (Vdc)- HF7 WALL,7008 (Vdc)- HF8 C3 ARC1,7009 (Vdc)- HF9 C3 ARC2,7010 (Vdc)- HF10 C3 DUAL1,7011 (Vdc)- HF11 C2 DUAL1
count,12580.000000,1.258000e+04,1.258000e+04,1.258000e+04,1.258000e+04,1.258000e+04,1.258000e+04,1.258000e+04,1.258000e+04,1.258000e+04,...,1.258000e+04,1.258000e+04,1.258000e+04,1.258000e+04,12580.000000,1.258000e+04,1.258000e+04,1.258000e+04,1.258000e+04,1.258000e+04
mean,6290.500000,5.744833e+35,5.902226e+35,6.217011e+35,4.328299e+35,5.351351e+35,4.328299e+35,4.879173e+35,4.564388e+35,4.249603e+35,...,-2.024177e-04,1.168544e-04,7.147749e-05,1.514815e-04,0.007093,2.073259e-04,4.877711e-05,1.022017e-04,1.455226e-04,7.473918e-05
std,3631.677528,7.519861e+36,7.621567e+36,7.820918e+36,6.531938e+36,7.259215e+36,6.531938e+36,6.933222e+36,6.706913e+36,6.472542e+36,...,1.256950e-02,1.336237e-02,2.236573e-03,6.185218e-03,0.044186,2.880065e-03,1.435319e-03,3.310421e-03,2.641377e-03,1.571022e-03
min,1.000000,-1.238020e+02,-1.975290e+02,-1.767940e+02,-1.752830e+02,-8.634200e+01,1.551500e+01,-7.833000e+00,1.533600e+01,-1.409090e+02,...,-1.016338e+00,-5.692921e-01,-1.118398e-01,-1.946402e-03,-1.192363,-1.006645e-01,-1.139135e-01,-5.603114e-02,-8.037980e-02,-1.232640e-04
25%,3145.750000,1.740350e+01,2.057900e+01,2.440600e+01,1.995500e+01,1.921050e+01,1.994475e+01,1.937800e+01,1.980400e+01,2.065000e+01,...,-1.068000e-06,-1.068000e-06,-6.790000e-07,-5.820000e-07,0.001107,3.880000e-07,-5.820000e-07,-6.790000e-07,-1.068000e-06,-7.760000e-07
50%,6290.500000,1.953300e+01,2.315700e+01,2.783500e+01,2.359850e+01,2.011500e+01,2.714300e+01,2.540950e+01,2.090850e+01,2.211050e+01,...,-5.820000e-07,-6.790000e-07,-2.910000e-07,-1.940000e-07,0.007416,9.710000e-07,-2.910000e-07,-2.910000e-07,-4.850000e-07,-2.910000e-07
75%,9435.250000,1.083465e+02,1.210045e+02,1.214988e+02,1.079340e+02,3.162950e+01,4.469475e+01,3.456850e+01,4.811800e+01,3.507200e+01,...,-9.700000e-08,-2.910000e-07,0.000000e+00,9.700000e-08,0.013324,1.747000e-06,9.700000e-08,0.000000e+00,-9.700000e-08,2.910000e-07
max,12580.000000,9.900000e+37,9.900000e+37,9.900000e+37,9.900000e+37,9.900000e+37,9.900000e+37,9.900000e+37,9.900000e+37,9.900000e+37,...,7.005935e-02,8.643902e-01,4.582471e-02,5.522392e-01,0.330207,7.378318e-02,4.481269e-02,1.789245e-01,1.518688e-01,8.536144e-02

In [5]:
df.dtypes

Scan Sweep Time (Sec)            str
Scan Number                    int64
3001 (°C)- TC1B              float64
3002 (°C)- TC2B              float64
3003 (°C)- TC3B              float64
                              ...
7007 (Vdc)- HF7 WALL         float64
7008 (Vdc)- HF8 C3 ARC1      float64
7009 (Vdc)- HF9 C3 ARC2      float64
7010 (Vdc)- HF10 C3 DUAL1    float64
7011 (Vdc)- HF11 C2 DUAL1    float64
Length: 106, dtype: object

In [ ]:
## check missing values..

df.isnull()

TypeError: unhashable type: 'DataFrame'

In [8]:
df.isnull().any()

Scan Sweep Time (Sec)        False
Scan Number                  False
3001 (°C)- TC1B              False
3002 (°C)- TC2B              False
3003 (°C)- TC3B              False
                             ...
7007 (Vdc)- HF7 WALL         False
7008 (Vdc)- HF8 C3 ARC1      False
7009 (Vdc)- HF9 C3 ARC2      False
7010 (Vdc)- HF10 C3 DUAL1    False
7011 (Vdc)- HF11 C2 DUAL1    False
Length: 106, dtype: bool

In [ ]:
df.isnull().sum()

Scan Sweep Time (Sec)        False
Scan Number                  False
3001 (°C)- TC1B              False
3002 (°C)- TC2B              False
3003 (°C)- TC3B              False
                             ...
7007 (Vdc)- HF7 WALL         False
7008 (Vdc)- HF8 C3 ARC1      False
7009 (Vdc)- HF9 C3 ARC2      False
7010 (Vdc)- HF10 C3 DUAL1    False
7011 (Vdc)- HF11 C2 DUAL1    False
Length: 106, dtype: bool

In [11]:
## renaming column...

df.rename(columns={'Scan Sweep Time (Sec)': "TimeStamp"})

,TimeStamp,Scan Number,3001 (°C)- TC1B,3002 (°C)- TC2B,3003 (°C)- TC3B,3004 (°C)- TC4B,3005 (°C)- TC5B,3006 (°C)- TC6B,3007 (°C)- TC7B,3008 (°C)- TC8B,...,7002 (Vdc)- HF2 C1 NE CORNER,7003 (Vdc)- HF3 C4 DUAL1,7004 (Vdc)- HF4 C4 ARC2,7005 (Vdc)- HF5 C3 ARC1,7006 (Vdc)- HF6 C1 N FRONT L,7007 (Vdc)- HF7 WALL,7008 (Vdc)- HF8 C3 ARC1,7009 (Vdc)- HF9 C3 ARC2,7010 (Vdc)- HF10 C3 DUAL1,7011 (Vdc)- HF11 C2 DUAL1
0,2025-11-19 22:02:13.703,1,17.121,17.284,16.990,16.949,15.796,15.578,15.607,15.462,...,8.740000e-07,-3.591000e-06,-8.444000e-06,-3.494000e-06,-2.910000e-07,-4.853000e-06,-5.921000e-06,-4.562000e-06,-1.028800e-05,-8.056000e-06
1,2025-11-19 22:02:18.274,2,17.092,17.277,16.969,16.950,15.792,15.566,15.605,15.462,...,3.494000e-06,-1.456000e-06,-2.524000e-06,-4.756000e-06,1.456000e-06,-1.553000e-06,-8.347000e-06,-7.765000e-06,-1.038500e-05,-3.688000e-06
2,2025-11-19 22:02:22.846,3,17.085,17.298,16.986,16.940,15.782,15.547,15.620,15.441,...,2.329000e-06,-1.165000e-06,-7.760000e-07,-2.135000e-06,9.700000e-08,-1.941000e-06,-8.347000e-06,-8.638000e-06,-8.250000e-06,-6.503000e-06
3,2025-11-19 22:02:27.418,4,17.084,17.266,16.980,16.946,15.747,15.537,15.600,15.464,...,2.718000e-06,-2.135000e-06,-1.359000e-06,-2.815000e-06,-9.700000e-08,4.850000e-07,-6.406000e-06,-6.503000e-06,-8.153000e-06,-7.473000e-06
4,2025-11-19 22:02:31.989,5,17.084,17.276,16.978,16.949,15.764,15.551,15.621,15.452,...,-2.910000e-07,-4.271000e-06,-3.979000e-06,-1.844000e-06,1.359000e-06,-1.359000e-06,-5.435000e-06,-4.465000e-06,-4.756000e-06,-5.823000e-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12575,2025-11-20 14:00:19.378,12576,19.739,19.177,21.597,13.691,20.114,46.020,34.311,21.367,...,-1.262000e-06,-9.710000e-07,0.000000e+00,0.000000e+00,2.304157e-03,-8.740000e-07,0.000000e+00,0.000000e+00,-1.262000e-06,-9.710000e-07
12576,2025-11-20 14:00:23.950,12577,19.786,19.049,21.455,13.583,20.118,46.459,34.331,21.445,...,-9.700000e-08,-1.262000e-06,-1.359000e-06,-5.820000e-07,1.081294e-02,3.880000e-07,-3.880000e-07,-1.940000e-07,-1.262000e-06,-5.820000e-07
12577,2025-11-20 14:00:28.521,12578,19.753,19.135,21.254,13.893,20.206,48.218,34.533,21.308,...,-6.790000e-07,-6.790000e-07,-4.850000e-07,-1.068000e-06,1.429558e-02,3.880000e-07,0.000000e+00,-1.262000e-06,-3.880000e-07,-9.700000e-08
12578,2025-11-20 14:00:33.092,12579,19.737,19.263,20.769,13.745,20.127,46.625,34.573,21.348,...,-2.910000e-07,-6.790000e-07,-5.820000e-07,-2.910000e-07,1.285534e-02,1.165000e-06,-2.910000e-07,-5.820000e-07,-7.760000e-07,-4.850000e-07
12579,2025-11-20 14:00:37.663,12580,19.720,19.403,21.060,14.070,20.294,46.651,34.439,21.331,...,2.910000e-07,-1.747000e-06,-3.880000e-07,-5.820000e-07,1.537545e-02,0.000000e+00,-2.910000e-07,-1.940000e-07,-9.700000e-08,-2.910000e-07

In [16]:
df['Scan Number_Float'] = df['Scan Number'].astype(float)
df.head()

,Scan Sweep Time (Sec),Scan Number,3001 (°C)- TC1B,3002 (°C)- TC2B,3003 (°C)- TC3B,3004 (°C)- TC4B,3005 (°C)- TC5B,3006 (°C)- TC6B,3007 (°C)- TC7B,3008 (°C)- TC8B,...,7004 (Vdc)- HF4 C4 ARC2,7005 (Vdc)- HF5 C3 ARC1,7006 (Vdc)- HF6 C1 N FRONT L,7007 (Vdc)- HF7 WALL,7008 (Vdc)- HF8 C3 ARC1,7009 (Vdc)- HF9 C3 ARC2,7010 (Vdc)- HF10 C3 DUAL1,7011 (Vdc)- HF11 C2 DUAL1,Change_dataType,Scan Number_Float
0,2025-11-19 22:02:13.703,1,17.121,17.284,16.990,16.949,15.796,15.578,15.607,15.462,...,-8.444000e-06,-0.000003,-2.910000e-07,-4.853000e-06,-0.000006,-0.000005,-0.000010,-0.000008,17,1.0
1,2025-11-19 22:02:18.274,2,17.092,17.277,16.969,16.950,15.792,15.566,15.605,15.462,...,-2.524000e-06,-0.000005,1.456000e-06,-1.553000e-06,-0.000008,-0.000008,-0.000010,-0.000004,17,2.0
2,2025-11-19 22:02:22.846,3,17.085,17.298,16.986,16.940,15.782,15.547,15.620,15.441,...,-7.760000e-07,-0.000002,9.700000e-08,-1.941000e-06,-0.000008,-0.000009,-0.000008,-0.000007,17,3.0
3,2025-11-19 22:02:27.418,4,17.084,17.266,16.980,16.946,15.747,15.537,15.600,15.464,...,-1.359000e-06,-0.000003,-9.700000e-08,4.850000e-07,-0.000006,-0.000007,-0.000008,-0.000007,17,4.0
4,2025-11-19 22:02:31.989,5,17.084,17.276,16.978,16.949,15.764,15.551,15.621,15.452,...,-3.979000e-06,-0.000002,1.359000e-06,-1.359000e-06,-0.000005,-0.000004,-0.000005,-0.000006,17,5.0

In [17]:
df['Scan Number_Double'] = df['Scan Number'].apply(lambda x: x**2)
df.head()

/tmp/ipykernel_201164/450756849.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['Scan Number_Double'] = df['Scan Number'].apply(lambda x: x**2)

,Scan Sweep Time (Sec),Scan Number,3001 (°C)- TC1B,3002 (°C)- TC2B,3003 (°C)- TC3B,3004 (°C)- TC4B,3005 (°C)- TC5B,3006 (°C)- TC6B,3007 (°C)- TC7B,3008 (°C)- TC8B,...,7005 (Vdc)- HF5 C3 ARC1,7006 (Vdc)- HF6 C1 N FRONT L,7007 (Vdc)- HF7 WALL,7008 (Vdc)- HF8 C3 ARC1,7009 (Vdc)- HF9 C3 ARC2,7010 (Vdc)- HF10 C3 DUAL1,7011 (Vdc)- HF11 C2 DUAL1,Change_dataType,Scan Number_Float,Scan Number_Double
0,2025-11-19 22:02:13.703,1,17.121,17.284,16.990,16.949,15.796,15.578,15.607,15.462,...,-0.000003,-2.910000e-07,-4.853000e-06,-0.000006,-0.000005,-0.000010,-0.000008,17,1.0,1
1,2025-11-19 22:02:18.274,2,17.092,17.277,16.969,16.950,15.792,15.566,15.605,15.462,...,-0.000005,1.456000e-06,-1.553000e-06,-0.000008,-0.000008,-0.000010,-0.000004,17,2.0,4
2,2025-11-19 22:02:22.846,3,17.085,17.298,16.986,16.940,15.782,15.547,15.620,15.441,...,-0.000002,9.700000e-08,-1.941000e-06,-0.000008,-0.000009,-0.000008,-0.000007,17,3.0,9
3,2025-11-19 22:02:27.418,4,17.084,17.266,16.980,16.946,15.747,15.537,15.600,15.464,...,-0.000003,-9.700000e-08,4.850000e-07,-0.000006,-0.000007,-0.000008,-0.000007,17,4.0,16
4,2025-11-19 22:02:31.989,5,17.084,17.276,16.978,16.949,15.764,15.551,15.621,15.452,...,-0.000002,1.359000e-06,-1.359000e-06,-0.000005,-0.000004,-0.000005,-0.000006,17,5.0,25